### PR TITLE
notify users

### PR DESCRIPTION
**Pull request by alphabard**
Notify users, sends user a dm with a notification message, Please merge 🙂

### CODE REVIEW

**Comment by Inferus-arch** [comment]
@alphabard What is the use of notification, please explain and i'll merge 👍🏼

**Comment by alphabard** [comment]
@Inferus-arch it can be used to notify user before you mute/unmute, kick or ban them 😄

**Comment by Inferus-arch** [comment]
@alphabard Okay i'll merge it 👍🏼

**Comment by alphabard** [comment]
ok thanks 😄

**Pull request merged**
